# Server Configuration
server:
  port: 8080

# Eureka Configuration
eureka:
  instance:
    status-page-url-path: ${server.contextPath:}/info
    health-check-url-path: ${server.contextPath:}/health
    hostname: ${reportportal.eureka.instance.hostname:localhost}
    metadata-map:
      extension: tfs

  client:
    serviceUrl:
      defaultZone: http://${reportportal.eureka.hostname:localhost}:8761/eureka/
    enabled: false
    register-with-eureka: false

# MongoDB configuration
rp:
  mongo:
    uri: mongodb://localhost:27017
    dbName: reportportal
    connectionsPerHost: 1000
    threadsAllowedToBlockForConnectionMultiplier: 1000
    connectTimeout: 20000
    socketTimeout: 60000
    maxWaitTime: 120000
    autoConnectRetry: true
    socketKeepAlive: true
    slaveOk: true
    writeTimeout: 0
    writeNumber: 1
    writeFsync: false
  cache:
    project:
      size: 1000
      expiration: 1
      info: 10
    ticket:
      size: 10000
      expiration: 5
    user:
      size: 1000
      expiration: 60

## OAUTH PRIVATE-PUBLIC keypair for TFS integration
oauth:
  certificate:
    store: oauth-keystore.jks

spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        tags:
        - urlprefix-${server.context-path:}/tfs opts strip=/tfs
        - traefik.frontend.rule=PathPrefixStrip:${server.context-path:}/tfs
        - statusPageUrlPath=${server.contextPath:}/info
        - healthCheckUrlPath=${server.contextPath:}/health
        - extension=tfs
        healthCheckPath: ${server.contextPath:}/health
        register: true
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        health-check-critical-timeout: 30s
      enabled: true
logging:
  level:
    com.netflix.discovery.shared.resolver: warn

## Consul as service registry
---
spring:
  profiles: consul
  cloud:
    consul:
      enabled: true
      discovery:
        register: true
eureka:
  client:
    register-with-eureka: false
    enabled: false

## Eureka as service registry
---
spring:
  profiles: eureka
  cloud:
    consul:
      enabled: false
      discovery:
        register: false
eureka:
  client:
    register-with-eureka: true
    enabled: true
---
